# Villa: Mac (left) + LG 43" horizontal (right)
[workspace-to-monitor-force-assignment]
1 = 'built-in'
2 = 'built-in'
3 = 'built-in'
4 = 'secondary'
5 = 'secondary'
6 = 'secondary'
7 = 'secondary'
8 = 'secondary'
9 = 'secondary'
